version: '3.8'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11.7
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=my
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password

  adminer:
    image: adminer:latest
    container_name: mariadb_adminer
    restart: always
    ports:
      - 18080:8080
    depends_on:
      - mariadb
    links:
      - mariadb

networks:
  default:
      name: mariadb_default_network