### member 전체 조회
GET localhost:8080/api/member

### member 단건 조회
@getId = 1
GET localhost:8080/api/member/{{getId}}

### member 등록
POST localhost:8080/api/member/create
Content-Type: application/json

{
  "name": "홍길동"
}

### member 수정
@updateId = 1
POST localhost:8080/api/member/update
Content-Type: application/json

{
  "id": {{updateId}},
  "name": "김길동"
}

### member 수정
@deleteId = 1
POST localhost:8080/api/member/delete
Content-Type: application/json

{
  "id": {{updateId}}
}